language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-git-snapshot-travis
script:
  - emacs --version
  - cask exec ert-runner -L . -L test

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis
