name: Run Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.version == 'snapshot'}}

    strategy:
      matrix:
        # Cask does't support Emacs 24.
        version: ['25.1', '25.2', '25.3', '26.1', '26.2', '26.3', '27.1', '27.2', '28.1', '28.2', 'snapshot']

    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.version }}
    - name: Run linters
      run: ./scripts/run_linter.sh
    - name: Run tests
      run: ./scripts/run_test.sh
